default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    upload_to_testflight(
      ipa: "../build/ios/ipa/medtrackaiflutter.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
