// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUItN3wcD15myQTiHYwCheIPFar5rUHi4',
    appId: '1:789677467574:android:986262c1eacd5466368317',
    messagingSenderId: '789677467574',
    projectId: 'gen-lang-client-0321454923',
    storageBucket: 'gen-lang-client-0321454923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2LYBTCTOyUoy-FgT-BzCbuD6qfawyn70',
    appId: '1:789677467574:ios:614a28899790fd30368317',
    messagingSenderId: '789677467574',
    projectId: 'gen-lang-client-0321454923',
    storageBucket: 'gen-lang-client-0321454923.firebasestorage.app',
    iosBundleId: 'com.medtracker.medtrackaiflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2LYBTCTOyUoy-FgT-BzCbuD6qfawyn70',
    appId: '1:789677467574:ios:614a28899790fd30368317',
    messagingSenderId: '789677467574',
    projectId: 'gen-lang-client-0321454923',
    storageBucket: 'gen-lang-client-0321454923.firebasestorage.app',
    iosBundleId: 'com.medtracker.medtrackaiflutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB--axAS4zybfCcpdCCPKkO0vh9khBts1o',
    appId: '1:789677467574:web:86e8caaaa05c6113368317',
    messagingSenderId: '789677467574',
    projectId: 'gen-lang-client-0321454923',
    authDomain: 'gen-lang-client-0321454923.firebaseapp.com',
    storageBucket: 'gen-lang-client-0321454923.firebasestorage.app',
    measurementId: 'G-NJRRHBZGB9',
  );

}